apiVersion: v1
appVersion: 4.5.1-b1557
description: Federator.ai helps enterprises optimize cloud resources, maximize application performance, and save significant cost without excessive over-provisioning or under-provisioning of resources, meeting the service-level requirements of their applications.
home: https://www.prophetstor.com
icon: https://raw.githubusercontent.com/prophetstor-ai/public/master/images/logo.png
keywords:
- AI
- Resource Orchestration
- NoOps
- AIOps
- Intelligent Workload Management
- Cost Optimization
maintainers:
- email: support@prophetstor.com
  name: ProphetStor Data Services, Inc.
name: federatorai
sources:
- https://www.prophetstor.com
version: "4.5.1"
