## Default values for Federator.ai
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
##
image:
  pullPolicy: IfNotPresent
  repository: repo.prophetservice.com/prophetstor/federatorai-operator-ubi
  tag: v4.5.1-b1557

## Set default values
##
federatorai:
  imageLocation: repo.prophetservice.com/prophetstor
  version: v4.5.1-b1557
  ## If thhe persistence is enabled, a default StorageClass
  ## is needed in the k8s cluster to provision volumes.
  persistence:
    enabled: false
    storageClass: ""
    storages:
      logStorage:
        size: 2Gi
    aiCore:
      dataStorage:
        size: 10Gi
    influxdb:
      dataStorage:
        size: 100Gi
    fedemeterInfluxdb:
      dataStorage:
        size: 10Gi

services:
  dashboardFrontend:
    ## Specify the nodePort value for the dashboard frontend
    ## Comment out the following line to disable nodePort service
    nodePort: 31012
  rest:
    ## Specify the nodePort value for the REST service
    ## Comment out the following line to disable nodePort service
    nodePort: 31011
