apiVersion: v1
kind: Service
metadata:
  labels:
    component: federatorai-operator
  name: federatorai-operator
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 50443
  selector:
    name: federatorai-operator
    app: Federator.ai